services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: goride-postgres
    environment:
      POSTGRES_DB: goride
      POSTGRES_USER: goride
      POSTGRES_PASSWORD: goride
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: goride-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
