package com.example.goride.analytics.model;

public enum AnalyticsQueryOperation {
    OVERVIEW,
    DEMAND_TIMESERIES,
    SUPPLY_TIMESERIES,
    DEMAND_HEATMAP,
    MATCHING_PERFORMANCE,
    MATCHING_FUNNEL,
    PROCESSING_STATUS,
    PROCESSING_RUNS,
    DATA_QUALITY,
    MODEL_VERSIONS,
    FORECAST_DEMAND,
    FORECAST_HOTSPOTS,
    FORECAST_EVALUATION,
    FORECAST_RUNS
}
